/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ActivityItem } from "./activityItem";

export interface ActivityCursorPage {
  readonly id?: string;
  readonly activities?: readonly ActivityItem[];
  readonly afterCursor?: string;
  readonly beforeCursor?: string;
  readonly hasAfter?: boolean;
  readonly hasBefore?: boolean;
  readonly reverse?: boolean;
  readonly $type?: string;
}
