/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ColumnSettings } from "./columnSettings";
import type { WIPLimit } from "./wIPLimit";
import type { AgileColumnFieldValue } from "./agileColumnFieldValue";

/**
 * Represents settings for a single board column
 */
export interface AgileColumn {
  readonly id?: string;
  readonly presentation?: string;
  readonly isResolved?: boolean;
  ordinal?: number;
  readonly parent?: ColumnSettings;
  wipLimit?: WIPLimit;
  fieldValues?: AgileColumnFieldValue[];
  readonly $type?: string;
}
