/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from "./user";
import type { UserGroup } from "./userGroup";
import type { AgileSharingSettings } from "./agileSharingSettings";
import type { CustomField } from "./customField";
import type { Project } from "./project";
import type { Sprint } from "./sprint";
import type { ColumnSettings } from "./columnSettings";
import type { SwimlaneSettings } from "./swimlaneSettings";
import type { SprintsSettings } from "./sprintsSettings";
import type { ColorCoding } from "./colorCoding";
import type { AgileStatus } from "./agileStatus";

export interface Agile {
  readonly id?: string;
  name?: string;
  owner?: User;
  visibleFor?: UserGroup;
  visibleForProjectBased?: boolean;
  updateableBy?: UserGroup;
  updateableByProjectBased?: boolean;
  readonly readSharingSettings?: AgileSharingSettings;
  readonly updateSharingSettings?: AgileSharingSettings;
  orphansAtTheTop?: boolean;
  hideOrphansSwimlane?: boolean;
  estimationField?: CustomField;
  originalEstimationField?: CustomField;
  projects?: Project[];
  sprints?: Sprint[];
  readonly currentSprint?: Sprint;
  readonly columnSettings?: ColumnSettings;
  swimlaneSettings?: SwimlaneSettings;
  readonly sprintsSettings?: SprintsSettings;
  colorCoding?: ColorCoding;
  readonly status?: AgileStatus;
  readonly $type?: string;
}
