/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { UserGroup } from "./userGroup";
import type { AllUsersGroupType } from "./allUsersGroupType";

/**
 * Represents a group containing all users including guest.
 */
export type AllUsersGroup = UserGroup & {
  $type: AllUsersGroupType;
};
