/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from "./user";
import type { Visibility } from "./visibility";
import type { BaseArticle } from "./baseArticle";
import type { ArticleComment } from "./articleComment";

export interface ArticleAttachment {
  readonly id?: string;
  name?: string;
  readonly author?: User;
  readonly created?: number;
  readonly updated?: number;
  readonly size?: number;
  readonly extension?: string;
  readonly charset?: string;
  readonly mimeType?: string;
  readonly metaData?: string;
  readonly draft?: boolean;
  readonly removed?: boolean;
  base64Content?: string;
  readonly url?: string;
  visibility?: Visibility;
  readonly article?: BaseArticle;
  readonly comment?: ArticleComment;
  readonly $type?: string;
}
