/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Article } from "./article";
import type { ArticleAttachment } from "./articleAttachment";
import type { User } from "./user";
import type { Reaction } from "./reaction";
import type { Visibility } from "./visibility";

export interface ArticleComment {
  readonly id?: string;
  readonly article?: Article;
  attachments?: ArticleAttachment[];
  readonly author?: User;
  readonly created?: number;
  pinned?: boolean;
  reactions?: Reaction[];
  text?: string;
  readonly updated?: number;
  visibility?: Visibility;
  readonly $type?: string;
}
