/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CreatedDeletedActivityItem } from "./createdDeletedActivityItem";
import type { AttachmentActivityItemAllOf } from "./attachmentActivityItemAllOf";
import type { AttachmentActivityItemType } from "./attachmentActivityItemType";

/**
 * Represents a change in the list of attachments of an issue.
 */
export type AttachmentActivityItem = CreatedDeletedActivityItem &
  AttachmentActivityItemAllOf & {
    $type: AttachmentActivityItemType;
  };
