/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { FilterField } from "./filterField";
import type { SwimlaneEntityAttributeValue } from "./swimlaneEntityAttributeValue";

export type AttributeBasedSwimlaneSettingsAllOf = {
  readonly id?: string;
  field?: FilterField;
  values?: SwimlaneEntityAttributeValue[];
};
