/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BackupError } from "./backupError";

export interface BackupStatus {
  readonly id?: string;
  readonly backupInProgress?: boolean;
  readonly backupCancelled?: boolean;
  readonly backupError?: BackupError;
  readonly $type?: string;
}
