/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Represents an error that appeared during the backup.
 */
export interface BackupError {
  readonly id?: string;
  readonly date?: number;
  readonly errorMessage?: string;
  readonly $type?: string;
}
