/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsHostingChangesProcessor } from "./vcsHostingChangesProcessor";
import type { BitBucketChangesProcessorAllOf } from "./bitBucketChangesProcessorAllOf";
import type { BitBucketChangesProcessorType } from "./bitBucketChangesProcessorType";

/**
 * Represents an integration with a VCS repository hosted on bitbucket.org.
 */
export type BitBucketChangesProcessor = VcsHostingChangesProcessor &
  BitBucketChangesProcessorAllOf & {
    $type: BitBucketChangesProcessorType;
  };
