/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsHostingServer } from "./vcsHostingServer";
import type { BitbucketStandaloneServerAllOf } from "./bitbucketStandaloneServerAllOf";
import type { BitbucketStandaloneServerType } from "./bitbucketStandaloneServerType";

/**
 * Represents a self-hosted Bitbucket server.
 */
export type BitbucketStandaloneServer = VcsHostingServer &
  BitbucketStandaloneServerAllOf & {
    $type: BitbucketStandaloneServerType;
  };
