/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleCustomFieldDefaults } from "./bundleCustomFieldDefaults";
import type { BuildBundleCustomFieldDefaultsAllOf } from "./buildBundleCustomFieldDefaultsAllOf";
import type { BuildBundleCustomFieldDefaultsType } from "./buildBundleCustomFieldDefaultsType";

/**
 * Default settings for the build-type field.
 */
export type BuildBundleCustomFieldDefaults = BundleCustomFieldDefaults &
  BuildBundleCustomFieldDefaultsAllOf & {
    $type: BuildBundleCustomFieldDefaultsType;
  };
