/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BaseBundle } from "./baseBundle";
import type { BuildBundleAllOf } from "./buildBundleAllOf";
import type { BuildBundleType } from "./buildBundleType";

export type BuildBundle = BaseBundle &
  BuildBundleAllOf & {
    $type: BuildBundleType;
  };
