/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type BundleProjectCustomFieldType =
  (typeof BundleProjectCustomFieldType)[keyof typeof BundleProjectCustomFieldType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BundleProjectCustomFieldType = {
  BundleProjectCustomField: "BundleProjectCustomField",
} as const;
