/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Bundle } from "./bundle";
import type { FieldStyle } from "./fieldStyle";
import type { BundleElementType } from "./bundleElementType";

/**
 * Represents a field value in YouTrack.
 */
export interface BundleElement {
  readonly id?: string;
  name?: string;
  readonly bundle?: Bundle;
  description?: string;
  archived?: boolean;
  ordinal?: number;
  color?: FieldStyle;
  readonly hasRunningJob?: boolean;
  $type: BundleElementType;
}
