/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsServer } from "./vcsServer";
import type { Project } from "./project";
import type { UserGroup } from "./userGroup";
import type { ChangesProcessorType } from "./changesProcessorType";

/**
 * The basic entity that represents a VCS or a build server integration configured for a project.
 */
export interface ChangesProcessor {
  readonly id?: string;
  readonly server?: VcsServer;
  project?: Project;
  relatedProjects?: Project[];
  enabled?: boolean;
  visibleForGroups?: UserGroup[];
  addComments?: boolean;
  lookupIssuesInBranchName?: boolean;
  $type: ChangesProcessorType;
}
