/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ColorCodingType } from "./colorCodingType";

/**
 * Describes rules that define which colors are used for cards on the agile board.
 */
export interface ColorCoding {
  readonly id?: string;
  $type: ColorCodingType;
}
