/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueComment } from "./issueComment";
import type { UserGroup } from "./userGroup";

export type CommentActivityItemAllOf = {
  readonly id?: string;
  readonly added?: readonly IssueComment[];
  readonly authorGroup?: UserGroup;
  readonly removed?: readonly IssueComment[];
  readonly target?: IssueComment;
};
