/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CommandVisibilityType } from "./commandVisibilityType";

/**
 * Visibility settings of the comment that is added along with the command.
 */
export interface CommandVisibility {
  readonly id?: string;
  $type: CommandVisibilityType;
}
