/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CommandVisibility } from "./commandVisibility";
import type { ParsedCommand } from "./parsedCommand";
import type { Issue } from "./issue";
import type { Suggestion } from "./suggestion";

export interface CommandList {
  readonly id?: string;
  comment?: string;
  visibility?: CommandVisibility;
  query?: string;
  caret?: number;
  silent?: boolean;
  runAs?: string;
  readonly commands?: readonly ParsedCommand[];
  issues?: Issue[];
  readonly suggestions?: readonly Suggestion[];
  readonly $type?: string;
}
