/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CustomField } from "./customField";

export type CustomFilterFieldAllOf = {
  readonly id?: string;
  readonly customField?: CustomField;
};
