/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ProjectCustomField } from "./projectCustomField";
import type { CustomFieldConditionType } from "./customFieldConditionType";

/**
 * Represents the condition for showing a custom field.
 */
export interface CustomFieldCondition {
  readonly id?: string;
  parent?: ProjectCustomField;
  $type: CustomFieldConditionType;
}
