/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueCustomField } from "./issueCustomField";
import type { DatabaseSingleValueIssueCustomFieldAllOf } from "./databaseSingleValueIssueCustomFieldAllOf";
import type { DatabaseSingleValueIssueCustomFieldType } from "./databaseSingleValueIssueCustomFieldType";

/**
 * Represents a a single-value custom field in the issue.
 */
export type DatabaseSingleValueIssueCustomField = IssueCustomField &
  DatabaseSingleValueIssueCustomFieldAllOf & {
    $type: DatabaseSingleValueIssueCustomFieldType;
  };
