/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseAttributeValueType } from "./databaseAttributeValueType";

/**
 * Represents string reference to the value.
 */
export interface DatabaseAttributeValue {
  readonly id?: string;
  $type: DatabaseAttributeValueType;
}
