/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { SimpleIssueCustomField } from "./simpleIssueCustomField";
import type { DateIssueCustomFieldAllOf } from "./dateIssueCustomFieldAllOf";
import type { DateIssueCustomFieldType } from "./dateIssueCustomFieldType";

/**
 * Represents a date-type custom field in the issue.
 */
export type DateIssueCustomField = SimpleIssueCustomField &
  DateIssueCustomFieldAllOf & {
    $type: DateIssueCustomFieldType;
  };
