/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { EmailSettingsMailProtocol } from "./emailSettingsMailProtocol";
import type { StorageEntry } from "./storageEntry";

/**
 * Represents email settings for this YouTrack installation.
 */
export interface EmailSettings {
  readonly id?: string;
  isEnabled?: boolean;
  host?: string;
  port?: number;
  mailProtocol?: EmailSettingsMailProtocol;
  anonymous?: boolean;
  login?: string;
  sslKey?: StorageEntry;
  from?: string;
  replyTo?: string;
  readonly $type?: string;
}
