/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type EmailSettingsMailProtocol =
  (typeof EmailSettingsMailProtocol)[keyof typeof EmailSettingsMailProtocol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmailSettingsMailProtocol = {
  SMTP: "SMTP",
  SMTPS: "SMTPS",
  SMTP_TLS: "SMTP_TLS",
} as const;
