/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { LocalizableBundleElement } from "./localizableBundleElement";
import type { EnumBundleElementAllOf } from "./enumBundleElementAllOf";
import type { EnumBundleElementType } from "./enumBundleElementType";

export type EnumBundleElement = LocalizableBundleElement &
  EnumBundleElementAllOf & {
    $type: EnumBundleElementType;
  };
