/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleProjectCustomField } from "./bundleProjectCustomField";
import type { EnumProjectCustomFieldAllOf } from "./enumProjectCustomFieldAllOf";
import type { EnumProjectCustomFieldType } from "./enumProjectCustomFieldType";

/**
 * Represents project settings for the enum field.
 */
export type EnumProjectCustomField = BundleProjectCustomField &
  EnumProjectCustomFieldAllOf & {
    $type: EnumProjectCustomFieldType;
  };
