/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Represents a transition from one value to another for a custom field that is managed by a state-machine rule in workflow.
 */
export interface Event {
  readonly id?: string;
  readonly presentation?: string;
  readonly $type?: string;
}
