/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * For an issue that was imported from another service, represents the reference to the issue in the external system.
 */
export interface ExternalIssue {
  readonly id?: string;
  readonly name?: string;
  readonly url?: string;
  readonly key?: string;
  readonly $type?: string;
}
