/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { FilterFieldType } from "./filterFieldType";

/**
 * Represents an issue property, which can be a predefined field, a custom field, a link, and so on.
 */
export interface FilterField {
  readonly id?: string;
  readonly presentation?: string;
  readonly name?: string;
  $type: FilterFieldType;
}
