/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DateFormatDescriptor } from "./dateFormatDescriptor";
import type { TimeZoneDescriptor } from "./timeZoneDescriptor";
import type { LocaleDescriptor } from "./localeDescriptor";

export interface GeneralUserProfile {
  readonly id?: string;
  dateFieldFormat?: DateFormatDescriptor;
  timezone?: TimeZoneDescriptor;
  locale?: LocaleDescriptor;
  readonly $type?: string;
}
