/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type GetIssuesIdActivitiesParams = {
  categories?: string;
  /**
 * Indicates whether the order of returning activities is from newest to oldest or the opposite.
If `false`, then the oldest activity item that matches a selected filter is returned first.
If `true`, then the newest activity is returned first. By default, `false`.
 */
  reverse?: boolean;
  /**
 * The timestamp in milliseconds indicating the start of the time interval the activity timestamp belongs to. 
Stored as a unix timestamp at UTC. 
If the parameter is not set, it is considered to be 0.
 */
  start?: string;
  /**
 * The timestamp in milliseconds indicating the end of the time interval the activity timestamp belongs to. 
Stored as a unix timestamp at UTC. 
If the parameter is not set, it is considered as `Long.MAX_VALUE`.
 */
  end?: string;
  /**
 * Parameter to filter activities by the author. You can specify one of the following parameters: the database ID, login, Hub ID,
or `me` for the currently logged in user.
 */
  author?: string;
  fields?: string;
  $skip?: number;
  $top?: number;
};
