/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type GetTagsParams = {
  /**
   * Tag search query. Use the name of the tag to filter the list of tags. To learn more about search queries, see <a href="api-query-syntax.topic">Query Syntax</a>.
   */
  query?: string;
  fields?: string;
  $skip?: number;
  $top?: number;
};
