/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsHostingChangesProcessor } from "./vcsHostingChangesProcessor";
import type { GiteaChangesProcessorAllOf } from "./giteaChangesProcessorAllOf";
import type { GiteaChangesProcessorType } from "./giteaChangesProcessorType";

/**
 * Represents a Gitea integration configured for a project.
 */
export type GiteaChangesProcessor = VcsHostingChangesProcessor &
  GiteaChangesProcessorAllOf & {
    $type: GiteaChangesProcessorType;
  };
