/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { GiteaServer } from "./giteaServer";

export type GiteaChangesProcessorAllOf = {
  readonly id?: string;
  readonly server?: GiteaServer;
};
