/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { WorkItemType } from "./workItemType";
import type { WorkTimeSettings } from "./workTimeSettings";
import type { WorkItemAttributePrototype } from "./workItemAttributePrototype";

export interface GlobalTimeTrackingSettings {
  readonly id?: string;
  readonly workItemTypes?: readonly WorkItemType[];
  readonly workTimeSettings?: WorkTimeSettings;
  readonly attributePrototypes?: readonly WorkItemAttributePrototype[];
  readonly $type?: string;
}
