/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { SystemSettings } from "./systemSettings";
import type { NotificationSettings } from "./notificationSettings";
import type { RestCorsSettings } from "./restCorsSettings";
import type { AppearanceSettings } from "./appearanceSettings";
import type { LocaleSettings } from "./localeSettings";
import type { License } from "./license";

export interface GlobalSettings {
  readonly id?: string;
  readonly systemSettings?: SystemSettings;
  readonly notificationSettings?: NotificationSettings;
  readonly restSettings?: RestCorsSettings;
  readonly appearanceSettings?: AppearanceSettings;
  readonly localeSettings?: LocaleSettings;
  readonly license?: License;
  readonly $type?: string;
}
