/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsHostingServer } from "./vcsHostingServer";
import type { GogsServerAllOf } from "./gogsServerAllOf";
import type { GogsServerType } from "./gogsServerType";

/**
 * Represents a Gogs server.
 */
export type GogsServer = VcsHostingServer &
  GogsServerAllOf & {
    $type: GogsServerType;
  };
