/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ProjectCustomField } from "./projectCustomField";
import type { GroupProjectCustomFieldAllOf } from "./groupProjectCustomFieldAllOf";
import type { GroupProjectCustomFieldType } from "./groupProjectCustomFieldType";

/**
 * Represents project settings for a group custom field.
 */
export type GroupProjectCustomField = ProjectCustomField &
  GroupProjectCustomFieldAllOf & {
    $type: GroupProjectCustomFieldType;
  };
