/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from "./user";
import type { Issue } from "./issue";

/**
 * Represents a user who subscribed for notifications about an issue.
 */
export interface IssueWatcher {
  readonly id?: string;
  readonly user?: User;
  readonly issue?: Issue;
  isStarred?: boolean;
  readonly $type?: string;
}
