/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueWatcher } from "./issueWatcher";

/**
 * Represents users that are subscribed to notifications about the issue.
 */
export interface IssueWatchers {
  readonly id?: string;
  hasStar?: boolean;
  issueWatchers?: IssueWatcher[];
  readonly duplicateWatchers?: readonly IssueWatcher[];
  readonly $type?: string;
}
