/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueWorkItem } from "./issueWorkItem";

export interface IssueTimeTracker {
  readonly id?: string;
  workItems?: IssueWorkItem[];
  readonly enabled?: boolean;
  readonly $type?: string;
}
