/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueAttachment } from "./issueAttachment";
import type { User } from "./user";
import type { Issue } from "./issue";
import type { Reaction } from "./reaction";
import type { Visibility } from "./visibility";

export interface IssueComment {
  readonly id?: string;
  attachments?: IssueAttachment[];
  readonly author?: User;
  readonly created?: number;
  deleted?: boolean;
  readonly issue?: Issue;
  pinned?: boolean;
  reactions?: Reaction[];
  text?: string;
  readonly textPreview?: string;
  readonly updated?: number;
  visibility?: Visibility;
  readonly $type?: string;
}
