/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from "./user";
import type { Visibility } from "./visibility";
import type { Issue } from "./issue";
import type { IssueComment } from "./issueComment";

export interface IssueAttachment {
  readonly id?: string;
  name?: string;
  readonly author?: User;
  readonly created?: number;
  readonly updated?: number;
  readonly size?: number;
  readonly extension?: string;
  readonly charset?: string;
  readonly mimeType?: string;
  readonly metaData?: string;
  readonly draft?: boolean;
  readonly removed?: boolean;
  base64Content?: string;
  readonly url?: string;
  visibility?: Visibility;
  readonly issue?: Issue;
  readonly comment?: IssueComment;
  readonly thumbnailURL?: string;
  readonly $type?: string;
}
