/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ProjectCustomField } from "./projectCustomField";
import type { IssueCustomFieldValue } from "./issueCustomFieldValue";
import type { IssueCustomFieldType } from "./issueCustomFieldType";

export interface IssueCustomField {
  readonly id?: string;
  readonly name?: string;
  readonly projectCustomField?: ProjectCustomField;
  readonly value?: IssueCustomFieldValue;
  $type: IssueCustomFieldType;
}
