/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from "./user";
import type { DuplicateVote } from "./duplicateVote";

/**
 * Represents users that have voted for the issue or its duplicates.
 */
export interface IssueVoters {
  readonly id?: string;
  hasVote?: boolean;
  readonly original?: readonly User[];
  readonly duplicate?: readonly DuplicateVote[];
  readonly $type?: string;
}
