/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { SimpleValueActivityItem } from "./simpleValueActivityItem";
import type { IssueResolvedActivityItemAllOf } from "./issueResolvedActivityItemAllOf";
import type { IssueResolvedActivityItemType } from "./issueResolvedActivityItemType";

/**
 * Represents an event when a user resolves an issue.
 */
export type IssueResolvedActivityItem = SimpleValueActivityItem &
  IssueResolvedActivityItemAllOf & {
    $type: IssueResolvedActivityItemType;
  };
