/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export interface License {
  readonly id?: string;
  username?: string;
  license?: string;
  readonly error?: string;
  readonly $type?: string;
}
