/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Represents a language locale that is used in UI.
 */
export interface LocaleDescriptor {
  readonly id?: string;
  readonly locale?: string;
  readonly language?: string;
  readonly community?: boolean;
  name?: string;
  readonly $type?: string;
}
