/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Company logo that is used in YouTrack.
 */
export interface Logo {
  readonly id?: string;
  readonly url?: string;
  readonly $type?: string;
}
