/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from "./user";
import type { MeAllOf } from "./meAllOf";
import type { MeType } from "./meType";

export type Me = User &
  MeAllOf & {
    $type: MeType;
  };
