/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ActivityItem } from "./activityItem";
import type { MultiValueActivityItemAllOf } from "./multiValueActivityItemAllOf";
import type { MultiValueActivityItemType } from "./multiValueActivityItemType";

/**
 * Represents a change in an entity attribute that has type of `Array of &lt;Entities&gt;`.
 */
export type MultiValueActivityItem = ActivityItem &
  MultiValueActivityItemAllOf & {
    $type: MultiValueActivityItemType;
  };
