/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseMultiValueIssueCustomField } from "./databaseMultiValueIssueCustomField";
import type { MultiEnumIssueCustomFieldAllOf } from "./multiEnumIssueCustomFieldAllOf";
import type { MultiEnumIssueCustomFieldType } from "./multiEnumIssueCustomFieldType";

/**
 * Represents a multi-value enum-type custom field in the issue.
 */
export type MultiEnumIssueCustomField = DatabaseMultiValueIssueCustomField &
  MultiEnumIssueCustomFieldAllOf & {
    $type: MultiEnumIssueCustomFieldType;
  };
