/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseMultiValueIssueCustomField } from "./databaseMultiValueIssueCustomField";
import type { MultiUserIssueCustomFieldAllOf } from "./multiUserIssueCustomFieldAllOf";
import type { MultiUserIssueCustomFieldType } from "./multiUserIssueCustomFieldType";

/**
 * Represents a multi-value user-type custom field in the issue.
 */
export type MultiUserIssueCustomField = DatabaseMultiValueIssueCustomField &
  MultiUserIssueCustomFieldAllOf & {
    $type: MultiUserIssueCustomFieldType;
  };
