/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleProjectCustomField } from "./bundleProjectCustomField";
import type { OwnedProjectCustomFieldAllOf } from "./ownedProjectCustomFieldAllOf";
import type { OwnedProjectCustomFieldType } from "./ownedProjectCustomFieldType";

/**
 * Represents project settings for an owned field.
 */
export type OwnedProjectCustomField = BundleProjectCustomField &
  OwnedProjectCustomFieldAllOf & {
    $type: OwnedProjectCustomFieldType;
  };
