/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleElement } from "./bundleElement";
import type { OwnedBundleElementAllOf } from "./ownedBundleElementAllOf";
import type { OwnedBundleElementType } from "./ownedBundleElementType";

export type OwnedBundleElement = BundleElement &
  OwnedBundleElementAllOf & {
    $type: OwnedBundleElementType;
  };
