/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Represents the command that was parsed from the provided query.
 */
export interface ParsedCommand {
  readonly id?: string;
  readonly description?: string;
  readonly error?: boolean;
  readonly delete?: boolean;
  readonly $type?: string;
}
