/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ProjectCustomField } from "./projectCustomField";
import type { PeriodProjectCustomFieldAllOf } from "./periodProjectCustomFieldAllOf";
import type { PeriodProjectCustomFieldType } from "./periodProjectCustomFieldType";

/**
 * Represents project settings for the period field.
 */
export type PeriodProjectCustomField = ProjectCustomField &
  PeriodProjectCustomFieldAllOf & {
    $type: PeriodProjectCustomFieldType;
  };
