/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueCustomField } from "./issueCustomField";
import type { PeriodIssueCustomFieldAllOf } from "./periodIssueCustomFieldAllOf";
import type { PeriodIssueCustomFieldType } from "./periodIssueCustomFieldType";

/**
 * Represents the period field in the issue.
 */
export type PeriodIssueCustomField = IssueCustomField &
  PeriodIssueCustomFieldAllOf & {
    $type: PeriodIssueCustomFieldType;
  };
