/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Represents the period field value.
 */
export interface PeriodValue {
  readonly id?: string;
  readonly minutes?: number;
  readonly presentation?: string;
  readonly $type?: string;
}
