/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type PostAgilesParams = {
  /**
   * The name of the board template that should be used. Possible values: `kanban`, `scrum`, `version`, `custom`, `personal`.
   */
  template?: string;
  fields?: string;
};
