/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from "./user";
import type { ProjectAllOfCustomFields } from "./projectAllOfCustomFields";
import type { Issue } from "./issue";
import type { UserGroup } from "./userGroup";

export type ProjectAllOf = {
  readonly id?: string;
  archived?: boolean;
  createdBy?: User;
  readonly customFields?: ProjectAllOfCustomFields;
  description?: string;
  fromEmail?: string;
  readonly iconUrl?: string;
  issues?: Issue[];
  leader?: User;
  name?: string;
  replyToEmail?: string;
  shortName?: string;
  startingNumber?: number;
  readonly team?: UserGroup;
  template?: boolean;
};
