/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ColorCoding } from "./colorCoding";
import type { ProjectBasedColorCodingAllOf } from "./projectBasedColorCodingAllOf";
import type { ProjectBasedColorCodingType } from "./projectBasedColorCodingType";

/**
 * Lets you set a color for a card based on its project.
 */
export type ProjectBasedColorCoding = ColorCoding &
  ProjectBasedColorCodingAllOf & {
    $type: ProjectBasedColorCodingType;
  };
