/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueFolder } from "./issueFolder";
import type { ProjectAllOf } from "./projectAllOf";
import type { ProjectType } from "./projectType";

export type Project = IssueFolder &
  ProjectAllOf & {
    $type: ProjectType;
  };
