/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { WatchFolder } from "./watchFolder";
import type { SavedQueryAllOf } from "./savedQueryAllOf";
import type { SavedQueryType } from "./savedQueryType";

export type SavedQuery = WatchFolder &
  SavedQueryAllOf & {
    $type: SavedQueryType;
  };
