/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { SingleValueActivityItem } from "./singleValueActivityItem";
import type { SimpleValueActivityItemAllOf } from "./simpleValueActivityItemAllOf";
import type { SimpleValueActivityItemType } from "./simpleValueActivityItemType";

/**
 * Represents the change in attributes of a simple type in the target entity:
Issue, IssueComment, WorkItem, IssueAttachment.
 */
export type SimpleValueActivityItem = SingleValueActivityItem &
  SimpleValueActivityItemAllOf & {
    $type: SimpleValueActivityItemType;
  };
