/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ActivityItem } from "./activityItem";
import type { SingleValueActivityItemAllOf } from "./singleValueActivityItemAllOf";
import type { SingleValueActivityItemType } from "./singleValueActivityItemType";

/**
 * Describe change of properties that can have single value.
 */
export type SingleValueActivityItem = ActivityItem &
  SingleValueActivityItemAllOf & {
    $type: SingleValueActivityItemType;
  };
