/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseSingleValueIssueCustomField } from "./databaseSingleValueIssueCustomField";
import type { SingleBuildIssueCustomFieldAllOf } from "./singleBuildIssueCustomFieldAllOf";
import type { SingleBuildIssueCustomFieldType } from "./singleBuildIssueCustomFieldType";

/**
 * Represents a single-value build-type custom field in the issue.
 */
export type SingleBuildIssueCustomField = DatabaseSingleValueIssueCustomField &
  SingleBuildIssueCustomFieldAllOf & {
    $type: SingleBuildIssueCustomFieldType;
  };
