/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseSingleValueIssueCustomField } from "./databaseSingleValueIssueCustomField";
import type { SingleVersionIssueCustomFieldAllOf } from "./singleVersionIssueCustomFieldAllOf";
import type { SingleVersionIssueCustomFieldType } from "./singleVersionIssueCustomFieldType";

/**
 * Represents a single-value version-type custom field in the issue.
 */
export type SingleVersionIssueCustomField =
  DatabaseSingleValueIssueCustomField &
    SingleVersionIssueCustomFieldAllOf & {
      $type: SingleVersionIssueCustomFieldType;
    };
