/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleProjectCustomField } from "./bundleProjectCustomField";
import type { StateProjectCustomFieldAllOf } from "./stateProjectCustomFieldAllOf";
import type { StateProjectCustomFieldType } from "./stateProjectCustomFieldType";

/**
 * Represents project settings for a state field.
 */
export type StateProjectCustomField = BundleProjectCustomField &
  StateProjectCustomFieldAllOf & {
    $type: StateProjectCustomFieldType;
  };
