/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleCustomFieldDefaults } from "./bundleCustomFieldDefaults";
import type { StateBundleCustomFieldDefaultsAllOf } from "./stateBundleCustomFieldDefaultsAllOf";
import type { StateBundleCustomFieldDefaultsType } from "./stateBundleCustomFieldDefaultsType";

/**
 * Default settings for the state-type field.
 */
export type StateBundleCustomFieldDefaults = BundleCustomFieldDefaults &
  StateBundleCustomFieldDefaultsAllOf & {
    $type: StateBundleCustomFieldDefaultsType;
  };
