/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { StateBundle } from "./stateBundle";
import type { StateBundleElement } from "./stateBundleElement";

export type StateProjectCustomFieldAllOf = {
  readonly id?: string;
  bundle?: StateBundle;
  defaultValues?: StateBundleElement[];
};
