/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseSingleValueIssueCustomField } from "./databaseSingleValueIssueCustomField";
import type { StateIssueCustomFieldAllOf } from "./stateIssueCustomFieldAllOf";
import type { StateIssueCustomFieldType } from "./stateIssueCustomFieldType";

/**
 * Represents a single-value state-type custom field in the issue.
 */
export type StateIssueCustomField = DatabaseSingleValueIssueCustomField &
  StateIssueCustomFieldAllOf & {
    $type: StateIssueCustomFieldType;
  };
