/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Represents query suggestion.
 */
export interface Suggestion {
  readonly id?: string;
  readonly completionStart?: number;
  readonly completionEnd?: number;
  readonly matchingStart?: number;
  readonly matchingEnd?: number;
  readonly caret?: number;
  readonly description?: string;
  readonly option?: string;
  readonly prefix?: string;
  readonly suffix?: string;
  readonly group?: string;
  readonly icon?: string;
  readonly auxiliaryIcon?: string;
  readonly className?: string;
  readonly $type?: string;
}
