/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { SwimlaneSettingsType } from "./swimlaneSettingsType";

/**
 * Base entity for different swimlane settings
 */
export interface SwimlaneSettings {
  readonly id?: string;
  enabled?: boolean;
  $type: SwimlaneSettingsType;
}
