/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Issue } from "./issue";
import type { FieldStyle } from "./fieldStyle";
import type { UserGroup } from "./userGroup";
import type { WatchFolderSharingSettings } from "./watchFolderSharingSettings";
import type { TagSharingSettings } from "./tagSharingSettings";

export type TagAllOf = {
  readonly id?: string;
  issues?: Issue[];
  color?: FieldStyle;
  untagOnResolve?: boolean;
  visibleFor?: UserGroup;
  updateableBy?: UserGroup;
  readonly readSharingSettings?: WatchFolderSharingSettings;
  readonly tagSharingSettings?: TagSharingSettings;
  readonly updateSharingSettings?: WatchFolderSharingSettings;
};
