/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { MultiValueActivityItem } from "./multiValueActivityItem";
import type { TagsActivityItemAllOf } from "./tagsActivityItemAllOf";
import type { TagsActivityItemType } from "./tagsActivityItemType";

/**
 * Represents a change in the list of tags of an issue.
 */
export type TagsActivityItem = MultiValueActivityItem &
  TagsActivityItemAllOf & {
    $type: TagsActivityItemType;
  };
