/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ChangesProcessor } from "./changesProcessor";
import type { TeamcityChangesProcessorAllOf } from "./teamcityChangesProcessorAllOf";
import type { TeamcityChangesProcessorType } from "./teamcityChangesProcessorType";

/**
 * Represents a TeamCity integration configured for a project.
 */
export type TeamcityChangesProcessor = ChangesProcessor &
  TeamcityChangesProcessorAllOf & {
    $type: TeamcityChangesProcessorType;
  };
