/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { TeamcityServer } from "./teamcityServer";

export type TeamcityChangesProcessorAllOf = {
  readonly id?: string;
  readonly server?: TeamcityServer;
};
