/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CustomFieldActivityItem } from "./customFieldActivityItem";
import type { TextCustomFieldActivityItemAllOf } from "./textCustomFieldActivityItemAllOf";
import type { TextCustomFieldActivityItemType } from "./textCustomFieldActivityItemType";

/**
 * Represents an activity that affects a custom field of the `text` type of an issue.
 */
export type TextCustomFieldActivityItem = CustomFieldActivityItem &
  TextCustomFieldActivityItemAllOf & {
    $type: TextCustomFieldActivityItemType;
  };
