/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Represents a value of the text field. Returns both source and rendered text.
 */
export interface TextFieldValue {
  readonly id?: string;
  readonly text?: string;
  readonly markdownText?: string;
  readonly $type?: string;
}
