/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type TextMarkupActivityItemType =
  (typeof TextMarkupActivityItemType)[keyof typeof TextMarkupActivityItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TextMarkupActivityItemType = {
  TextMarkupActivityItem: "TextMarkupActivityItem",
} as const;
