/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Issue } from "./issue";

export type TextCustomFieldActivityItemAllOf = {
  readonly id?: string;
  readonly added?: string;
  readonly markup?: string;
  readonly removed?: string;
  readonly target?: Issue;
};
