/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Visibility } from "./visibility";
import type { UnlimitedVisibilityType } from "./unlimitedVisibilityType";

/**
 * Represents unlimited visibility. When access to an entity is not restricted, the visibility attribute of this entity has the type `UnlimitedVisibility`. Entities of this type do not have any attributes.
 */
export type UnlimitedVisibility = Visibility & {
  $type: UnlimitedVisibilityType;
};
