/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleProjectCustomField } from "./bundleProjectCustomField";
import type { UserProjectCustomFieldAllOf } from "./userProjectCustomFieldAllOf";
import type { UserProjectCustomFieldType } from "./userProjectCustomFieldType";

/**
 * Represents project settings for a user field.
 */
export type UserProjectCustomField = BundleProjectCustomField &
  UserProjectCustomFieldAllOf & {
    $type: UserProjectCustomFieldType;
  };
