/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Project } from "./project";
import type { UserGroupType } from "./userGroupType";

export interface UserGroup {
  readonly id?: string;
  readonly name?: string;
  readonly ringId?: string;
  readonly usersCount?: number;
  readonly icon?: string;
  readonly allUsersGroup?: boolean;
  readonly teamForProject?: Project;
  $type: UserGroupType;
}
