/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Bundle } from "./bundle";
import type { UserBundleAllOf } from "./userBundleAllOf";
import type { UserBundleType } from "./userBundleType";

export type UserBundle = Bundle &
  UserBundleAllOf & {
    $type: UserBundleType;
  };
