/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsChange } from "./vcsChange";
import type { User } from "./user";

export type VcsChangeActivityItemAllOf = {
  readonly id?: string;
  readonly removed?: readonly VcsChange[];
  readonly added?: readonly VcsChange[];
  readonly author?: User;
};
