/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsServer } from "./vcsServer";
import type { VcsHostingServerAllOf } from "./vcsHostingServerAllOf";
import type { VcsHostingServerType } from "./vcsHostingServerType";

/**
 * The basic entity that represents a VCS server.
 */
export type VcsHostingServer = VcsServer &
  VcsHostingServerAllOf & {
    $type: VcsHostingServerType;
  };
