/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsServerType } from "./vcsServerType";

/**
 * The basic entity that represents a VCS or a build server.
 */
export interface VcsServer {
  readonly id?: string;
  url?: string;
  $type: VcsServerType;
}
