/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VersionBundle } from "./versionBundle";
import type { VersionBundleElement } from "./versionBundleElement";

export type VersionProjectCustomFieldAllOf = {
  readonly id?: string;
  bundle?: VersionBundle;
  defaultValues?: VersionBundleElement[];
};
