/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleCustomFieldDefaults } from "./bundleCustomFieldDefaults";
import type { VersionBundleCustomFieldDefaultsAllOf } from "./versionBundleCustomFieldDefaultsAllOf";
import type { VersionBundleCustomFieldDefaultsType } from "./versionBundleCustomFieldDefaultsType";

/**
 * Default settings for the version-type field.
 */
export type VersionBundleCustomFieldDefaults = BundleCustomFieldDefaults &
  VersionBundleCustomFieldDefaultsAllOf & {
    $type: VersionBundleCustomFieldDefaultsType;
  };
