/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { MultiValueActivityItem } from "./multiValueActivityItem";
import type { VisibilityActivityItemAllOf } from "./visibilityActivityItemAllOf";
import type { VisibilityActivityItemType } from "./visibilityActivityItemType";

/**
 * Represents the changes of properties responsible for visibility restriction.
Can be <a href="api-entity-VisibilityGroupActivityItem.topic">VisibilityGroupActivityItem</a> or <a href="api-entity-VisibilityUserActivityItem.topic">VisibilityUserActivityItem</a>
 */
export type VisibilityActivityItem = MultiValueActivityItem &
  VisibilityActivityItemAllOf & {
    $type: VisibilityActivityItemType;
  };
