/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VisibilityType } from "./visibilityType";

/**
 * Represents visibility settings of an entity, for example, an issue or a comment.
 */
export interface Visibility {
  readonly id?: string;
  $type: VisibilityType;
}
