/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VisibilityActivityItem } from "./visibilityActivityItem";
import type { VisibilityGroupActivityItemAllOf } from "./visibilityGroupActivityItemAllOf";
import type { VisibilityGroupActivityItemType } from "./visibilityGroupActivityItemType";

/**
 * Represents the event when a user adds or removes a group to/from the Visibility settings of the target entity.
 */
export type VisibilityGroupActivityItem = VisibilityActivityItem &
  VisibilityGroupActivityItemAllOf & {
    $type: VisibilityGroupActivityItemType;
  };
