/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { MultiValueActivityItem } from "./multiValueActivityItem";
import type { VotersActivityItemAllOf } from "./votersActivityItemAllOf";
import type { VotersActivityItemType } from "./votersActivityItemType";

/**
 * Represents a change in the list of voters of an issue.
 */
export type VotersActivityItem = MultiValueActivityItem &
  VotersActivityItemAllOf & {
    $type: VotersActivityItemType;
  };
