/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from "./user";
import type { Issue } from "./issue";

export type VotersActivityItemAllOf = {
  readonly id?: string;
  readonly added?: readonly User[];
  readonly removed?: readonly User[];
  readonly target?: Issue;
};
