/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueFolder } from "./issueFolder";
import type { WatchFolderAllOf } from "./watchFolderAllOf";
import type { WatchFolderType } from "./watchFolderType";

/**
 * `WatchFolder` is a common abstract ancestor for saved searches and tags.
 */
export type WatchFolder = IssueFolder &
  WatchFolderAllOf & {
    $type: WatchFolderType;
  };
