/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from "./user";
import type { UserGroup } from "./userGroup";
import type { WatchFolderSharingSettings } from "./watchFolderSharingSettings";

export type WatchFolderAllOf = {
  readonly id?: string;
  readonly owner?: User;
  visibleFor?: UserGroup;
  updateableBy?: UserGroup;
  readonly readSharingSettings?: WatchFolderSharingSettings;
  readonly updateSharingSettings?: WatchFolderSharingSettings;
};
