/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { AgileColumn } from "./agileColumn";

/**
 * Represents WIP limits for particular column. If they are not satisfied, the column will be highlighted in UI.
 */
export interface WIPLimit {
  readonly id?: string;
  max?: number;
  min?: number;
  column?: AgileColumn;
  readonly $type?: string;
}
