/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CreatedDeletedActivityItem } from "./createdDeletedActivityItem";
import type { WorkItemActivityItemAllOf } from "./workItemActivityItemAllOf";
import type { WorkItemActivityItemType } from "./workItemActivityItemType";

/**
 * Represents a change in a list of work items in an issue.
 */
export type WorkItemActivityItem = CreatedDeletedActivityItem &
  WorkItemActivityItemAllOf & {
    $type: WorkItemActivityItemType;
  };
