/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ProjectTimeTrackingSettings } from "./projectTimeTrackingSettings";
import type { WorkItemAttributePrototype } from "./workItemAttributePrototype";
import type { WorkItemAttributeValue } from "./workItemAttributeValue";

/**
 * Represents the project-related settings of a work item attribute.
 */
export interface WorkItemProjectAttribute {
  readonly id?: string;
  timeTrackingSettings?: ProjectTimeTrackingSettings;
  prototype?: WorkItemAttributePrototype;
  values?: WorkItemAttributeValue[];
  readonly name?: string;
  ordinal?: number;
  readonly $type?: string;
}
