/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { SingleValueActivityItem } from "./singleValueActivityItem";
import type { WorkItemDurationActivityItemAllOf } from "./workItemDurationActivityItemAllOf";
import type { WorkItemDurationActivityItemType } from "./workItemDurationActivityItemType";

/**
 * Represents a change in the `duration` attribute of a work item.
 */
export type WorkItemDurationActivityItem = SingleValueActivityItem &
  WorkItemDurationActivityItemAllOf & {
    $type: WorkItemDurationActivityItemType;
  };
