/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { WorkItemProjectAttribute } from "./workItemProjectAttribute";
import type { WorkItemAttributeValue } from "./workItemAttributeValue";

/**
 * Represents a work item attribute prototype that is common for all projects. The project-related settings for work item attributes are stored in the `WorkItemProjectAttribute` entities.
 */
export interface WorkItemAttributePrototype {
  readonly id?: string;
  name?: string;
  instances?: WorkItemProjectAttribute[];
  values?: WorkItemAttributeValue[];
  readonly $type?: string;
}
