/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export interface WorkTimeSettings {
  readonly id?: string;
  minutesADay?: number;
  workDays?: number[];
  readonly firstDayOfWeek?: number;
  readonly daysAWeek?: number;
  readonly $type?: string;
}
