/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type WorkItemAuthorActivityItemType =
  (typeof WorkItemAuthorActivityItemType)[keyof typeof WorkItemAuthorActivityItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkItemAuthorActivityItemType = {
  WorkItemAuthorActivityItem: "WorkItemAuthorActivityItem",
} as const;
