/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseAttributeValue } from './databaseAttributeValue';
import type { AgileColumnFieldValueAllOf } from './agileColumnFieldValueAllOf';
import type { AgileColumnFieldValueType } from './agileColumnFieldValueType';

/**
 * Represents a field value or values, parameterizing agile column.
 */
export type AgileColumnFieldValue = DatabaseAttributeValue & AgileColumnFieldValueAllOf & {
  $type: AgileColumnFieldValueType;
};
