/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Shows if the board has any configuration problems.
 */
export interface AgileStatus {
  readonly id?: string;
  readonly valid?: boolean;
  readonly hasJobs?: boolean;
  readonly errors?: readonly string[];
  readonly warnings?: readonly string[];
  readonly $type?: string;
}
