/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BaseArticle } from './baseArticle';
import type { ArticleAllOf } from './articleAllOf';
import type { ArticleType } from './articleType';

export type Article = BaseArticle & ArticleAllOf & {
  $type: ArticleType;
};
