/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ArticleAttachment } from './articleAttachment';
import type { Article } from './article';
import type { ArticleComment } from './articleComment';
import type { ExternalArticle } from './externalArticle';
import type { Project } from './project';
import type { User } from './user';
import type { Tag } from './tag';
import type { Visibility } from './visibility';

export type ArticleAllOf = {
  readonly id?: string;
  attachments?: ArticleAttachment[];
  childArticles?: Article[];
  comments?: ArticleComment[];
  content?: string;
  readonly created?: number;
  readonly externalArticle?: ExternalArticle;
  readonly hasChildren?: boolean;
  hasStar?: boolean;
  readonly idReadable?: string;
  readonly ordinal?: number;
  parentArticle?: Article;
  readonly pinnedComments?: readonly ArticleComment[];
  readonly project?: Project;
  reporter?: User;
  summary?: string;
  tags?: Tag[];
  readonly updated?: number;
  readonly updatedBy?: User;
  visibility?: Visibility;
};
