/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueAttachment } from './issueAttachment';

export type AttachmentActivityItemAllOf = {
  readonly id?: string;
  readonly added?: readonly IssueAttachment[];
  readonly removed?: readonly IssueAttachment[];
  readonly target?: IssueAttachment;
};
