/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export interface BackupFile {
  readonly id?: string;
  readonly name?: string;
  readonly size?: number;
  readonly creationDate?: number;
  readonly link?: string;
  readonly $type?: string;
}
