/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ArticleAttachment } from './articleAttachment';
import type { User } from './user';
import type { Visibility } from './visibility';
import type { BaseArticleType } from './baseArticleType';

/**
 * Represents a base article entity.
 */
export interface BaseArticle {
  readonly id?: string;
  attachments?: ArticleAttachment[];
  content?: string;
  reporter?: User;
  summary?: string;
  visibility?: Visibility;
  $type: BaseArticleType;
}
