/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Bundle } from './bundle';
import type { BaseBundleAllOf } from './baseBundleAllOf';
import type { BaseBundleType } from './baseBundleType';

/**
 * Represents a set of field values in YouTrack.
 */
export type BaseBundle = Bundle & BaseBundleAllOf & {
  $type: BaseBundleType;
};
