/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BaseWorkItemType } from './baseWorkItemType';

/**
 * Represents a basic ancestor for work items.
 */
export interface BaseWorkItem {
  readonly id?: string;
  $type: BaseWorkItemType;
}
