/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsHostingServer } from './vcsHostingServer';
import type { BitBucketServerAllOf } from './bitBucketServerAllOf';
import type { BitBucketServerType } from './bitBucketServerType';

/**
 * Represents a cloud Bitbucket server.
 */
export type BitBucketServer = VcsHostingServer & BitBucketServerAllOf & {
  $type: BitBucketServerType;
};
