/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsHostingChangesProcessor } from './vcsHostingChangesProcessor';
import type { BitbucketStandaloneChangesProcessorAllOf } from './bitbucketStandaloneChangesProcessorAllOf';
import type { BitbucketStandaloneChangesProcessorType } from './bitbucketStandaloneChangesProcessorType';

/**
 * Represents an integration with a VCS repository on a self-hosted Bitbucket server.
 */
export type BitbucketStandaloneChangesProcessor = VcsHostingChangesProcessor & BitbucketStandaloneChangesProcessorAllOf & {
  $type: BitbucketStandaloneChangesProcessorType;
};
