/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleProjectCustomField } from './bundleProjectCustomField';
import type { BuildProjectCustomFieldAllOf } from './buildProjectCustomFieldAllOf';
import type { BuildProjectCustomFieldType } from './buildProjectCustomFieldType';

/**
 * Represents project settings for a build field.
 */
export type BuildProjectCustomField = BundleProjectCustomField & BuildProjectCustomFieldAllOf & {
  $type: BuildProjectCustomFieldType;
};
