/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleType } from './bundleType';

export interface Bundle {
  readonly id?: string;
  readonly isUpdateable?: boolean;
  $type: BundleType;
}
