/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CustomFieldDefaults } from './customFieldDefaults';
import type { BundleCustomFieldDefaultsAllOf } from './bundleCustomFieldDefaultsAllOf';
import type { BundleCustomFieldDefaultsType } from './bundleCustomFieldDefaultsType';

/**
 * Represents custom field default settings for enumerated fields.
 */
export type BundleCustomFieldDefaults = CustomFieldDefaults & BundleCustomFieldDefaultsAllOf & {
  $type: BundleCustomFieldDefaultsType;
};
