/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { MultiValueActivityItem } from './multiValueActivityItem';
import type { CommentAttachmentsActivityItemAllOf } from './commentAttachmentsActivityItemAllOf';
import type { CommentAttachmentsActivityItemType } from './commentAttachmentsActivityItemType';

/**
 * Represents a change in the `attachments` attribute of an IssueComment.
 */
export type CommentAttachmentsActivityItem = MultiValueActivityItem & CommentAttachmentsActivityItemAllOf & {
  $type: CommentAttachmentsActivityItemType;
};
