/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CreatedDeletedActivityItem } from './createdDeletedActivityItem';
import type { CommentActivityItemAllOf } from './commentActivityItemAllOf';
import type { CommentActivityItemType } from './commentActivityItemType';

/**
 * Represents a change in the comments of an issue.
 */
export type CommentActivityItem = CreatedDeletedActivityItem & CommentActivityItemAllOf & {
  $type: CommentActivityItemType;
};
