/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ActivityItem } from './activityItem';
import type { CreatedDeletedActivityItemAllOf } from './createdDeletedActivityItemAllOf';
import type { CreatedDeletedActivityItemType } from './createdDeletedActivityItemType';

/**
 * Represents an action when an entity is created or deleted in an issue. For example, a new comment is created in the issue.
 */
export type CreatedDeletedActivityItem = ActivityItem & CreatedDeletedActivityItemAllOf & {
  $type: CreatedDeletedActivityItemType;
};
