/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ActivityItem } from './activityItem';
import type { CustomFieldActivityItemAllOf } from './customFieldActivityItemAllOf';
import type { CustomFieldActivityItemType } from './customFieldActivityItemType';

/**
 * Represents an activity that affects a custom field of an issue.
 */
export type CustomFieldActivityItem = ActivityItem & CustomFieldActivityItemAllOf & {
  $type: CustomFieldActivityItemType;
};
