/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CustomFieldActivityItemAllOfAdded } from './customFieldActivityItemAllOfAdded';
import type { CustomFieldActivityItemAllOfRemoved } from './customFieldActivityItemAllOfRemoved';
import type { Issue } from './issue';

export type CustomFieldActivityItemAllOf = {
  readonly id?: string;
  readonly added?: CustomFieldActivityItemAllOfAdded;
  readonly removed?: CustomFieldActivityItemAllOfRemoved;
  readonly target?: Issue;
};
