/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { FieldType } from './fieldType';
import type { CustomFieldDefaults } from './customFieldDefaults';
import type { ProjectCustomField } from './projectCustomField';

export interface CustomField {
  readonly id?: string;
  name?: string;
  localizedName?: string;
  fieldType?: FieldType;
  isAutoAttached?: boolean;
  isDisplayedInIssueList?: boolean;
  ordinal?: number;
  aliases?: string;
  readonly fieldDefaults?: CustomFieldDefaults;
  readonly hasRunningJob?: boolean;
  readonly isUpdateable?: boolean;
  instances?: ProjectCustomField[];
  readonly $type?: string;
}
