/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueCustomField } from './issueCustomField';
import type { DatabaseMultiValueIssueCustomFieldAllOf } from './databaseMultiValueIssueCustomFieldAllOf';
import type { DatabaseMultiValueIssueCustomFieldType } from './databaseMultiValueIssueCustomFieldType';

/**
 * Represents a custom field that may have multiple values in the issue.
 */
export type DatabaseMultiValueIssueCustomField = IssueCustomField & DatabaseMultiValueIssueCustomFieldAllOf & {
  $type: DatabaseMultiValueIssueCustomFieldType;
};
