/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseBackupSettingsArchiveFormat } from './databaseBackupSettingsArchiveFormat';
import type { User } from './user';
import type { BackupStatus } from './backupStatus';

export interface DatabaseBackupSettings {
  readonly id?: string;
  location?: string;
  filesToKeep?: number;
  cronExpression?: string;
  archiveFormat?: DatabaseBackupSettingsArchiveFormat;
  isOn?: boolean;
  readonly availableDiskSpace?: number;
  notifiedUsers?: User[];
  readonly backupStatus?: BackupStatus;
  readonly $type?: string;
}
