/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Issue } from './issue';
import type { User } from './user';

/**
 * Represents a vote for duplicates of the issue.
 */
export interface DuplicateVote {
  readonly id?: string;
  readonly issue?: Issue;
  readonly user?: User;
  readonly $type?: string;
}
