/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Represents the duration value and its visual presentation.
 */
export interface DurationValue {
  readonly id?: string;
  readonly minutes?: number;
  readonly presentation?: string;
  readonly $type?: string;
}
