/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleCustomFieldDefaults } from './bundleCustomFieldDefaults';
import type { EnumBundleCustomFieldDefaultsAllOf } from './enumBundleCustomFieldDefaultsAllOf';
import type { EnumBundleCustomFieldDefaultsType } from './enumBundleCustomFieldDefaultsType';

/**
 * Default settings for the enum-type field.
 */
export type EnumBundleCustomFieldDefaults = BundleCustomFieldDefaults & EnumBundleCustomFieldDefaultsAllOf & {
  $type: EnumBundleCustomFieldDefaultsType;
};
