/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * For an article that was imported from another service, this entity represents the reference to the article in the external system.
 */
export interface ExternalArticle {
  readonly id?: string;
  readonly name?: string;
  readonly url?: string;
  readonly key?: string;
  readonly $type?: string;
}
