/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Represents the style settings of the field in YouTrack.
 */
export interface FieldStyle {
  readonly id?: string;
  readonly background?: string;
  readonly foreground?: string;
  readonly $type?: string;
}
