/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CustomFieldCondition } from './customFieldCondition';
import type { FieldBasedConditionAllOf } from './fieldBasedConditionAllOf';
import type { FieldBasedConditionType } from './fieldBasedConditionType';

/**
 * Represents the condition for showing a custom field.
 */
export type FieldBasedCondition = CustomFieldCondition & FieldBasedConditionAllOf & {
  $type: FieldBasedConditionType;
};
