/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ColorCoding } from './colorCoding';
import type { FieldBasedColorCodingAllOf } from './fieldBasedColorCodingAllOf';
import type { FieldBasedColorCodingType } from './fieldBasedColorCodingType';

/**
 * Sets a card color based on a value of some custom field.
 */
export type FieldBasedColorCoding = ColorCoding & FieldBasedColorCodingAllOf & {
  $type: FieldBasedColorCodingType;
};
