/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type FilterFieldType = typeof FilterFieldType[keyof typeof FilterFieldType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FilterFieldType = {
  FilterField: 'FilterField',
} as const;
