/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type GetWorkItemsParams = {
/**
 * Issue search query. Read more about the search syntax here: <a href="https://www.jetbrains.com/help/youtrack/cloud/?Search-and-Command-Attributes">Search Query Reference</a>
 */
query?: string;
/**
 * The start date of the time interval where the work item dates belong. Accepts a date in a string format: `YYYY-MM-DD`.
 */
startDate?: Date;
/**
 * The end date of the time interval where the work item dates belong. Accepts a date in a string format: `YYYY-MM-DD`.
 */
endDate?: Date;
/**
 * A timestamp in milliseconds indicating the start of the interval where the work item dates belong.
 */
start?: number;
/**
 * A timestamp in milliseconds indicating the end of the interval where the work item dates belong.
 */
end?: number;
/**
 * A timestamp in milliseconds indicating the start of the interval during which work items were created.
 */
createdStart?: number;
/**
 * A timestamp in milliseconds indicating the end of the interval during which work items were created.
 */
createdEnd?: number;
/**
 * A timestamp in milliseconds indicating the start of the interval during which work items were updated.
 */
updatedStart?: number;
/**
 * A timestamp in milliseconds indicating the end of the interval during which work items were updated.
 */
updatedEnd?: number;
author?: string;
creator?: string;
fields?: string;
$skip?: number;
$top?: number;
};
