/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsHostingServer } from './vcsHostingServer';
import type { GiteaServerAllOf } from './giteaServerAllOf';
import type { GiteaServerType } from './giteaServerType';

/**
 * Represents a Gitea server.
 */
export type GiteaServer = VcsHostingServer & GiteaServerAllOf & {
  $type: GiteaServerType;
};
