/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VcsHostingServer } from './vcsHostingServer';
import type { GitHubServerAllOf } from './gitHubServerAllOf';
import type { GitHubServerType } from './gitHubServerType';

/**
 * Represents a GitHub server.
 */
export type GitHubServer = VcsHostingServer & GitHubServerAllOf & {
  $type: GitHubServerType;
};
