/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { SwimlaneSettings } from './swimlaneSettings';
import type { IssueBasedSwimlaneSettingsAllOf } from './issueBasedSwimlaneSettingsAllOf';
import type { IssueBasedSwimlaneSettingsType } from './issueBasedSwimlaneSettingsType';

/**
 * Swimlane settings for the case, when each swimlane is represented by an issue and contains this issue's subtasks.
 */
export type IssueBasedSwimlaneSettings = SwimlaneSettings & IssueBasedSwimlaneSettingsAllOf & {
  $type: IssueBasedSwimlaneSettingsType;
};
