/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueLinkDirection } from './issueLinkDirection';
import type { IssueLinkType } from './issueLinkType';
import type { Issue } from './issue';

export interface IssueLink {
  readonly id?: string;
  readonly direction?: IssueLinkDirection;
  readonly linkType?: IssueLinkType;
  issues?: Issue[];
  readonly trimmedIssues?: readonly Issue[];
  readonly $type?: string;
}
