/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export interface IssueLinkType {
  readonly id?: string;
  name?: string;
  localizedName?: string;
  sourceToTarget?: string;
  localizedSourceToTarget?: string;
  targetToSource?: string;
  localizedTargetToSource?: string;
  directed?: boolean;
  aggregation?: boolean;
  readonly readOnly?: boolean;
  readonly $type?: string;
}
