/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from './user';
import type { WorkItemType } from './workItemType';
import type { DurationValue } from './durationValue';
import type { Issue } from './issue';
import type { WorkItemAttribute } from './workItemAttribute';

export type IssueWorkItemAllOf = {
  readonly id?: string;
  author?: User;
  readonly creator?: User;
  text?: string;
  readonly textPreview?: string;
  type?: WorkItemType;
  created?: number;
  updated?: number;
  duration?: DurationValue;
  date?: number;
  readonly issue?: Issue;
  readonly attributes?: readonly WorkItemAttribute[];
};
