/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CreatedDeletedActivityItem } from './createdDeletedActivityItem';
import type { IssueCreatedActivityItemAllOf } from './issueCreatedActivityItemAllOf';
import type { IssueCreatedActivityItemType } from './issueCreatedActivityItemType';

/**
 * Represents an event when a user creates a new issue.
 */
export type IssueCreatedActivityItem = CreatedDeletedActivityItem & IssueCreatedActivityItemAllOf & {
  $type: IssueCreatedActivityItemType;
};
