/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueAttachment } from './issueAttachment';
import type { IssueComment } from './issueComment';
import type { IssueCustomField } from './issueCustomField';
import type { User } from './user';
import type { ExternalIssue } from './externalIssue';
import type { IssueLink } from './issueLink';
import type { Project } from './project';
import type { Tag } from './tag';
import type { Visibility } from './visibility';
import type { IssueVoters } from './issueVoters';
import type { IssueWatchers } from './issueWatchers';

export interface Issue {
  readonly id?: string;
  attachments?: IssueAttachment[];
  comments?: IssueComment[];
  readonly commentsCount?: number;
  readonly created?: number;
  readonly customFields?: readonly IssueCustomField[];
  description?: string;
  readonly draftOwner?: User;
  readonly externalIssue?: ExternalIssue;
  readonly idReadable?: string;
  readonly isDraft?: boolean;
  readonly links?: readonly IssueLink[];
  readonly numberInProject?: number;
  readonly parent?: IssueLink;
  readonly pinnedComments?: readonly IssueComment[];
  project?: Project;
  readonly reporter?: User;
  readonly resolved?: number;
  readonly subtasks?: IssueLink;
  summary?: string;
  tags?: Tag[];
  readonly updated?: number;
  readonly updater?: User;
  visibility?: Visibility;
  readonly voters?: IssueVoters;
  readonly votes?: number;
  readonly watchers?: IssueWatchers;
  readonly wikifiedDescription?: string;
  readonly $type?: string;
}
