/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Visibility } from './visibility';
import type { LimitedVisibilityAllOf } from './limitedVisibilityAllOf';
import type { LimitedVisibilityType } from './limitedVisibilityType';

/**
 * Represents visibility limited to several users and/or groups.
 */
export type LimitedVisibility = Visibility & LimitedVisibilityAllOf & {
  $type: LimitedVisibilityType;
};
