/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { MultiValueActivityItemAllOfAdded } from './multiValueActivityItemAllOfAdded';
import type { MultiValueActivityItemAllOfRemoved } from './multiValueActivityItemAllOfRemoved';

export type MultiValueActivityItemAllOf = {
  readonly id?: string;
  readonly added?: MultiValueActivityItemAllOfAdded;
  readonly removed?: MultiValueActivityItemAllOfRemoved;
};
