/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseMultiValueIssueCustomField } from './databaseMultiValueIssueCustomField';
import type { MultiVersionIssueCustomFieldAllOf } from './multiVersionIssueCustomFieldAllOf';
import type { MultiVersionIssueCustomFieldType } from './multiVersionIssueCustomFieldType';

/**
 * Represents a multi-value version-type custom field in the issue.
 */
export type MultiVersionIssueCustomField = DatabaseMultiValueIssueCustomField & MultiVersionIssueCustomFieldAllOf & {
  $type: MultiVersionIssueCustomFieldType;
};
