/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseMultiValueIssueCustomField } from './databaseMultiValueIssueCustomField';
import type { MultiOwnedIssueCustomFieldAllOf } from './multiOwnedIssueCustomFieldAllOf';
import type { MultiOwnedIssueCustomFieldType } from './multiOwnedIssueCustomFieldType';

/**
 * Represents a multi-value owned-type custom field in the issue.
 */
export type MultiOwnedIssueCustomField = DatabaseMultiValueIssueCustomField & MultiOwnedIssueCustomFieldAllOf & {
  $type: MultiOwnedIssueCustomFieldType;
};
