/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { BundleCustomFieldDefaults } from './bundleCustomFieldDefaults';
import type { OwnedBundleCustomFieldDefaultsAllOf } from './ownedBundleCustomFieldDefaultsAllOf';
import type { OwnedBundleCustomFieldDefaultsType } from './ownedBundleCustomFieldDefaultsType';

/**
 * Default settings for the owned-type field.
 */
export type OwnedBundleCustomFieldDefaults = BundleCustomFieldDefaults & OwnedBundleCustomFieldDefaultsAllOf & {
  $type: OwnedBundleCustomFieldDefaultsType;
};
