/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

/**
 * Represents the format, in which the period values are displayed to the user.
 */
export interface PeriodFieldFormat {
  readonly id?: string;
  readonly $type?: string;
}
