/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type PostAdminProjectsParams = {
/**
 * If the `template` is not specified, then the new project will use the default settings.
<emphasis>Optional</emphasis>. Lets you specify the template to use for the new project.
Possible values: `scrum`, `kanban`.
 */
template?: string;
fields?: string;
};
