/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { FilterField } from './filterField';
import type { PredefinedFilterFieldAllOf } from './predefinedFilterFieldAllOf';
import type { PredefinedFilterFieldType } from './predefinedFilterFieldType';

/**
 * Represents a predefined field of the issue. Predefined fields are always present in an issue and
            |cannot be customized in a project. For example, `project`, `created`,
            |`updated`, `tags`, and so on.
 */
export type PredefinedFilterField = FilterField & PredefinedFilterFieldAllOf & {
  $type: PredefinedFilterFieldType;
};
