/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ProjectCustomField } from './projectCustomField';
import type { WorkItemType } from './workItemType';
import type { Project } from './project';
import type { WorkItemProjectAttribute } from './workItemProjectAttribute';

export interface ProjectTimeTrackingSettings {
  readonly id?: string;
  enabled?: boolean;
  estimate?: ProjectCustomField;
  timeSpent?: ProjectCustomField;
  workItemTypes?: WorkItemType[];
  readonly project?: Project;
  attributes?: WorkItemProjectAttribute[];
  readonly $type?: string;
}
