/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CustomField } from './customField';
import type { Project } from './project';
import type { CustomFieldCondition } from './customFieldCondition';
import type { ProjectCustomFieldType } from './projectCustomFieldType';

export interface ProjectCustomField {
  readonly id?: string;
  readonly field?: CustomField;
  readonly project?: Project;
  canBeEmpty?: boolean;
  emptyFieldText?: string;
  ordinal?: number;
  isPublic?: boolean;
  readonly hasRunningJob?: boolean;
  condition?: CustomFieldCondition;
  $type: ProjectCustomFieldType;
}
