/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { SingleValueActivityItem } from './singleValueActivityItem';
import type { ProjectActivityItemAllOf } from './projectActivityItemAllOf';
import type { ProjectActivityItemType } from './projectActivityItemType';

/**
 * Represents the change in the project attribute on an issue.
 */
export type ProjectActivityItem = SingleValueActivityItem & ProjectActivityItemAllOf & {
  $type: ProjectActivityItemType;
};
