/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from './user';

export interface Reaction {
  readonly id?: string;
  author?: User;
  reaction?: string;
  readonly $type?: string;
}
