/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ProjectCustomField } from './projectCustomField';
import type { SimpleProjectCustomFieldAllOf } from './simpleProjectCustomFieldAllOf';
import type { SimpleProjectCustomFieldType } from './simpleProjectCustomFieldType';

/**
 * Represents project settings for the fields of the following types: `integer`, `float`, `date`, `date and time`, `string`.
 */
export type SimpleProjectCustomField = ProjectCustomField & SimpleProjectCustomFieldAllOf & {
  $type: SimpleProjectCustomFieldType;
};
