/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueCustomField } from './issueCustomField';
import type { SimpleIssueCustomFieldAllOf } from './simpleIssueCustomFieldAllOf';
import type { SimpleIssueCustomFieldType } from './simpleIssueCustomFieldType';

/**
 * Represents a simple-type custom field in the issue.
 */
export type SimpleIssueCustomField = IssueCustomField & SimpleIssueCustomFieldAllOf & {
  $type: SimpleIssueCustomFieldType;
};
