/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export type SingleValueActivityItemType = typeof SingleValueActivityItemType[keyof typeof SingleValueActivityItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SingleValueActivityItemType = {
  SingleValueActivityItem: 'SingleValueActivityItem',
} as const;
