/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseSingleValueIssueCustomField } from './databaseSingleValueIssueCustomField';
import type { SingleGroupIssueCustomFieldAllOf } from './singleGroupIssueCustomFieldAllOf';
import type { SingleGroupIssueCustomFieldType } from './singleGroupIssueCustomFieldType';

/**
 * Represents a single-value group-type custom field in the issue.
 */
export type SingleGroupIssueCustomField = DatabaseSingleValueIssueCustomField & SingleGroupIssueCustomFieldAllOf & {
  $type: SingleGroupIssueCustomFieldType;
};
