/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseSingleValueIssueCustomField } from './databaseSingleValueIssueCustomField';
import type { SingleUserIssueCustomFieldAllOf } from './singleUserIssueCustomFieldAllOf';
import type { SingleUserIssueCustomFieldType } from './singleUserIssueCustomFieldType';

/**
 * Represents a single-value user-type custom field in the issue.
 */
export type SingleUserIssueCustomField = DatabaseSingleValueIssueCustomField & SingleUserIssueCustomFieldAllOf & {
  $type: SingleUserIssueCustomFieldType;
};
