/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseSingleValueIssueCustomField } from './databaseSingleValueIssueCustomField';
import type { SingleOwnedIssueCustomFieldAllOf } from './singleOwnedIssueCustomFieldAllOf';
import type { SingleOwnedIssueCustomFieldType } from './singleOwnedIssueCustomFieldType';

/**
 * Represents a single-value owned-type custom field in the issue.
 */
export type SingleOwnedIssueCustomField = DatabaseSingleValueIssueCustomField & SingleOwnedIssueCustomFieldAllOf & {
  $type: SingleOwnedIssueCustomFieldType;
};
