/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseSingleValueIssueCustomField } from './databaseSingleValueIssueCustomField';
import type { SingleEnumIssueCustomFieldAllOf } from './singleEnumIssueCustomFieldAllOf';
import type { SingleEnumIssueCustomFieldType } from './singleEnumIssueCustomFieldType';

/**
 * Represents a single-value enum-type custom field in the issue.
 */
export type SingleEnumIssueCustomField = DatabaseSingleValueIssueCustomField & SingleEnumIssueCustomFieldAllOf & {
  $type: SingleEnumIssueCustomFieldType;
};
