/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Agile } from './agile';
import type { Issue } from './issue';

export interface Sprint {
  readonly id?: string;
  readonly agile?: Agile;
  name?: string;
  goal?: string;
  start?: number;
  finish?: number;
  archived?: boolean;
  isDefault?: boolean;
  issues?: Issue[];
  readonly unresolvedIssuesCount?: number;
  previousSprint?: Sprint;
  readonly $type?: string;
}
