/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { MultiValueActivityItem } from './multiValueActivityItem';
import type { SprintActivityItemAllOf } from './sprintActivityItemAllOf';
import type { SprintActivityItemType } from './sprintActivityItemType';

/**
 * Represents a change in the issue when it was added to or removed from an agile board sprint.
 */
export type SprintActivityItem = MultiValueActivityItem & SprintActivityItemAllOf & {
  $type: SprintActivityItemType;
};
