/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Sprint } from './sprint';
import type { CustomField } from './customField';

/**
 * Describes sprints configuration.
 */
export interface SprintsSettings {
  readonly id?: string;
  isExplicit?: boolean;
  cardOnSeveralSprints?: boolean;
  defaultSprint?: Sprint;
  disableSprints?: boolean;
  explicitQuery?: string;
  sprintSyncField?: CustomField;
  hideSubtasksOfCards?: boolean;
  readonly $type?: string;
}
