/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseSingleValueIssueCustomField } from './databaseSingleValueIssueCustomField';
import type { StateMachineIssueCustomFieldAllOf } from './stateMachineIssueCustomFieldAllOf';
import type { StateMachineIssueCustomFieldType } from './stateMachineIssueCustomFieldType';

/**
 * Represents the issue custom field that is managed by a state-machine rule in workflow.
 */
export type StateMachineIssueCustomField = DatabaseSingleValueIssueCustomField & StateMachineIssueCustomFieldAllOf & {
  $type: StateMachineIssueCustomFieldType;
};
