/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { DatabaseAttributeValue } from './databaseAttributeValue';
import type { SwimlaneEntityAttributeValueAllOf } from './swimlaneEntityAttributeValueAllOf';
import type { SwimlaneEntityAttributeValueType } from './swimlaneEntityAttributeValueType';

/**
 * Represents a single swimlane in case of AttributeBasedSwimlaneSettings.
 */
export type SwimlaneEntityAttributeValue = DatabaseAttributeValue & SwimlaneEntityAttributeValueAllOf & {
  $type: SwimlaneEntityAttributeValueType;
};
