/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */

export interface SystemSettings {
  readonly id?: string;
  baseUrl?: string;
  maxUploadFileSize?: number;
  maxExportItems?: number;
  administratorEmail?: string;
  allowStatisticsCollection?: boolean;
  isApplicationReadOnly?: boolean;
  readonly $type?: string;
}
