/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { OnlineUsers } from './onlineUsers';

export interface Telemetry {
  readonly id?: string;
  readonly installationFolder?: string;
  readonly databaseLocation?: string;
  readonly logsLocation?: string;
  readonly availableProcessors?: number;
  readonly availableMemory?: string;
  readonly allocatedMemory?: string;
  readonly usedMemory?: string;
  readonly uptime?: string;
  readonly startedTime?: number;
  readonly databaseBackgroundThreads?: number;
  readonly pendingAsyncJobs?: number;
  readonly cachedResultsCountInDBQueriesCache?: number;
  readonly databaseQueriesCacheHitRate?: string;
  readonly blobStringsCacheHitRate?: string;
  readonly totalTransactions?: number;
  readonly transactionsPerSecond?: string;
  readonly requestsPerSecond?: string;
  readonly databaseSize?: string;
  readonly fullDatabaseSize?: string;
  readonly textIndexSize?: string;
  readonly onlineUsers?: OnlineUsers;
  readonly reportCalculatorThreads?: number;
  readonly notificationAnalyzerThreads?: number;
  readonly $type?: string;
}
