/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueCustomField } from './issueCustomField';
import type { TextIssueCustomFieldAllOf } from './textIssueCustomFieldAllOf';
import type { TextIssueCustomFieldType } from './textIssueCustomFieldType';

/**
 * Represents the issue custom field of the `text` type.
 */
export type TextIssueCustomField = IssueCustomField & TextIssueCustomFieldAllOf & {
  $type: TextIssueCustomFieldType;
};
