/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { Tag } from './tag';
import type { SavedQuery } from './savedQuery';
import type { UserProfiles } from './userProfiles';
import type { UserType } from './userType';

export interface User {
  readonly id?: string;
  readonly login?: string;
  readonly fullName?: string;
  readonly email?: string;
  readonly ringId?: string;
  readonly guest?: boolean;
  readonly online?: boolean;
  readonly banned?: boolean;
  readonly tags?: readonly Tag[];
  readonly savedQueries?: readonly SavedQuery[];
  readonly avatarUrl?: string;
  readonly profiles?: UserProfiles;
  $type: UserType;
}
