/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { UserBundle } from './userBundle';
import type { User } from './user';

export type UserProjectCustomFieldAllOf = {
  readonly id?: string;
  bundle?: UserBundle;
  defaultValues?: User[];
};
