/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CustomFieldDefaults } from './customFieldDefaults';
import type { UserCustomFieldDefaultsAllOf } from './userCustomFieldDefaultsAllOf';
import type { UserCustomFieldDefaultsType } from './userCustomFieldDefaultsType';

/**
 * Represents default settings for the user-type field.
 */
export type UserCustomFieldDefaults = CustomFieldDefaults & UserCustomFieldDefaultsAllOf & {
  $type: UserCustomFieldDefaultsType;
};
