/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { CreatedDeletedActivityItem } from './createdDeletedActivityItem';
import type { VcsChangeActivityItemAllOf } from './vcsChangeActivityItemAllOf';
import type { VcsChangeActivityItemType } from './vcsChangeActivityItemType';

/**
 * Represents an update in the list of VCS changes of an issue.
 */
export type VcsChangeActivityItem = CreatedDeletedActivityItem & VcsChangeActivityItemAllOf & {
  $type: VcsChangeActivityItemType;
};
