/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from './user';
import type { ChangesProcessor } from './changesProcessor';
import type { Issue } from './issue';

export interface VcsChange {
  readonly id?: string;
  readonly date?: number;
  readonly fetched?: number;
  readonly files?: number;
  readonly author?: User;
  readonly processors?: readonly ChangesProcessor[];
  readonly text?: string;
  readonly urls?: readonly string[];
  version?: string;
  issue?: Issue;
  state?: number;
  readonly $type?: string;
}
