/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { ChangesProcessor } from './changesProcessor';
import type { VcsHostingChangesProcessorAllOf } from './vcsHostingChangesProcessorAllOf';
import type { VcsHostingChangesProcessorType } from './vcsHostingChangesProcessorType';

/**
 * The basic entity that represents a VCS integration configured for a project.
 */
export type VcsHostingChangesProcessor = ChangesProcessor & VcsHostingChangesProcessorAllOf & {
  $type: VcsHostingChangesProcessorType;
};
