/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from './user';
import type { VcsUnresolvedUserAllOf } from './vcsUnresolvedUserAllOf';
import type { VcsUnresolvedUserType } from './vcsUnresolvedUserType';

/**
 * Represents a VCS change author who could not be associated with any YouTrack user account.
 */
export type VcsUnresolvedUser = User & VcsUnresolvedUserAllOf & {
  $type: VcsUnresolvedUserType;
};
