/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { VisibilityActivityItem } from './visibilityActivityItem';
import type { VisibilityUserActivityItemAllOf } from './visibilityUserActivityItemAllOf';
import type { VisibilityUserActivityItemType } from './visibilityUserActivityItemType';

/**
 * Represents the event when a user adds or removes a user to/from the Visibility settings of the target entity.
 */
export type VisibilityUserActivityItem = VisibilityActivityItem & VisibilityUserActivityItemAllOf & {
  $type: VisibilityUserActivityItemType;
};
