/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { User } from './user';

export type VisibilityUserActivityItemAllOf = {
  readonly id?: string;
  readonly added?: readonly User[];
  readonly removed?: readonly User[];
  readonly targetMember?: string;
  readonly targetSubMember?: string;
};
