/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { SingleValueActivityItem } from './singleValueActivityItem';
import type { WorkItemAuthorActivityItemAllOf } from './workItemAuthorActivityItemAllOf';
import type { WorkItemAuthorActivityItemType } from './workItemAuthorActivityItemType';

/**
 * Represents a change in the `author` attribute of a work item.
 */
export type WorkItemAuthorActivityItem = SingleValueActivityItem & WorkItemAuthorActivityItemAllOf & {
  $type: WorkItemAuthorActivityItemType;
};
