/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { WorkItemAttributePrototype } from './workItemAttributePrototype';

/**
 * Represents a value of a work item attribute.
 */
export interface WorkItemAttributeValue {
  readonly id?: string;
  name?: string;
  description?: string;
  autoAttach?: boolean;
  prototype?: WorkItemAttributePrototype;
  readonly $type?: string;
}
