/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 * OpenAPI spec version: 2025.1
 */
import type { IssueWorkItem } from './issueWorkItem';
import type { User } from './user';

export type WorkItemAuthorActivityItemAllOf = {
  readonly id?: string;
  readonly target?: IssueWorkItem;
  readonly removed?: User;
  readonly added?: User;
};
